apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dan
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/danedmunds/argocd-example-apps
      revision: master
      directories:
      - path: applications/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: qcs
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/danedmunds/argocd-example-apps
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default